### ISSUE TITLE
Tracking issue for non-Rusty designs in vm.rs / vm.c

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#4]
`vm` 관련 코드를 옮기면서 마주친 Rust스럽지 않은 디자인의 목록입니다.

- [ ] `wait_entries`: array 길이가 32 이상이면 현재 Rust에서는 `Default::default()` 로 쉽게 초기화할 수 없습니다.
  - __vm.c에서는__: 루프를 돌면서 초기화하는 것으로 만들었습니다.
  - __현재 Rust 구현은__: `mem::uninitalized()` 로 둔 다음 초기화하는 것으로 만들었습니다.
- [ ] `VM_MANAGER`: `ArrayVec` 이 constant initializer를 가지지 않아서 직관적인 초기화 코드를 사용할 수 없습니다.
  - 방법 1: `unsafe { mem::uninitialized() }` 로 초기화하기. 이 함수 또한 const가 아니라서 불가능.
  - 방법 2: `unsafe { MaybeUninit::uninit().assume_init() }`로 초기화하기. 마찬가지로 const가 아니라서 불가능.
  - 방법 3: `lazy_static` 또는 그와 비슷한 일을 하는 코드. C코드와 semantics가 달라집니다.
  - __현재 Rust 구현은__: bss 영역이 0으로 초기화되고, `ArrayVec`의 초기화 코드 또한 인덱스를 0으로 초기화하는 것 뿐이므로 그냥 초기화 코드를 작성하지 않습니다. (`MaybeUninit::uninit()`로 초기화하고 `ArrayVec::new()`는 어디에서도 호출하지 않습니다.)
- [ ] `spci_vm_id_t`, `spci_vcpu_count_t` 등: 이런 류의 타입이 `uint16_t` 로 정의되어 `usize`와 맞지 않습니다.
- [ ] `vm_init`: c 코드에서는 전역 배열에서 원소의 포인터를 가져와서 바로 그 자리에 초기화합니다.
  - __현재 Rust 구현은__: `Vm::new()`의 결과를 `ArrayVec`에 푸시합니다. move propagation 최적화가 아주 똑똑하다면 c 코드와 동일하게 작동하지 않을까요?
- [ ] `vm_locked`: `mm_stage1_locked` 와 달리 `api.c` 에서 내부 `vm` field를 접근하기 때문에 단순히 `SpinLockGuard<VmState>`의 주소를 저장하는 것으로 구현할 수 없습니다.
  - __현재 Rust 구현은__: `state`의 lock을 걸고 `vm`의 주소를 저장하도록 했습니다.
- [x] `arch_vm`: architecture-specific한 구조의 field `arch_vm`를 `Vm` 내에 만들어야 합니다.
- [x] `VmManager`: static 변수로 선언하기 위해서 `Sync`를 강제로 태깅했습니다. 내부 필드를 고쳐서 Rust가 추론할 수 있도록 고쳐야 합니다.

**Comment by jeehoonkang** [comment]
- `wait_entries`: 더이상 relevant하지 않은 것 같습니다.
- `VM_MANAGER`: 더이상 relevant하지 않은 것 같습니다.
- `spci_vm_id_t`: 이건 원래 코드가 `u16`이지 않나요?  그럼 우리가 바꾸긴 어려울 것 같습니다.
- `vm_init`: 더이상 relevant하지 않은 것 같습니다.
- `vm_locked`: `VmLocked`를 RAII 스타일로 바꿔야 한다고 생각합니다. `VCpuExecutionLocked`처럼..
