### ISSUE TITLE
Tracking issue: apply refactorings to upstream

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#79]
- [ ] `page` type
 - [ ] Wrapping `pte_t` by `page_table_entry`
 - [ ] Separate non-fallback `mpool`.
 - [ ] Split protected-by-lock fields.
 - [ ] Split `vcpu` lock: #78
 - [ ] Gather global variables into `hypervisor` singleton.
